first pass avx2 compile/runtime integration

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -584,7 +584,8 @@ PACKAGE_URL=
 ac_unique_file="DESCRIPTION"
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-ADDITIONAL_FLAGS
+AVX2_FLAGS
+OMP_FLAGS
 OPENMP_CFLAGS
 OBJEXT
 EXEEXT
@@ -1790,6 +1791,18 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
+# Get C compiler from R
+: ${R_HOME=`R RHOME`}
+if test -z "${R_HOME}"; then
+  echo "could not determine R_HOME"
+  exit 1
+fi
+CC=`"${R_HOME}/bin/R" CMD config CC`
+CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
+CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
+
+
 ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
@@ -2758,7 +2771,6 @@ fi
 
 
 
-
   OPENMP_CFLAGS=
   # Check whether --enable-openmp was given.
 if test "${enable_openmp+set}" = set; then :
@@ -2824,14 +2836,72 @@ $as_echo "$ac_cv_prog_c_openmp" >&6; }
   fi
 
 
-
 if test -n "${OPENMP_CFLAGS}"; then
-  ADDITIONAL_FLAGS="\$(SHLIB_OPENMP_CFLAGS)"
+  have_omp="yes"
+  OMP_FLAGS="\$(SHLIB_OPENMP_CFLAGS)"
 else
-  ADDITIONAL_FLAGS=""
+  have_omp="no"
+  OMP_FLAGS=""
 fi
 
-echo $ADDITIONAL_FLAGS
+
+
+as_CACHEVAR=`$as_echo "ax_cv_check_cflags__"-mavx2"" | $as_tr_sh`
+{ $as_echo "$as_me:${as_lineno-$LINENO}: checking whether C compiler accepts \"-mavx2\"" >&5
+$as_echo_n "checking whether C compiler accepts \"-mavx2\"... " >&6; }
+if eval \${$as_CACHEVAR+:} false; then :
+  $as_echo_n "(cached) " >&6
+else
+
+  ax_check_save_flags=$CFLAGS
+  CFLAGS="$CFLAGS  "-mavx2""
+  cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+int
+main ()
+{
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_c_try_compile "$LINENO"; then :
+  eval "$as_CACHEVAR=yes"
+else
+  eval "$as_CACHEVAR=no"
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+  CFLAGS=$ax_check_save_flags
+fi
+eval ac_res=\$$as_CACHEVAR
+	       { $as_echo "$as_me:${as_lineno-$LINENO}: result: $ac_res" >&5
+$as_echo "$ac_res" >&6; }
+if eval test \"x\$"$as_CACHEVAR"\" = x"yes"; then :
+  have_avx2="yes"
+else
+  have_avx2="no"
+fi
+
+if test "X${have_avx2}" = Xyes; then
+  AVX2_FLAGS="-mavx2"
+else
+  AVX2_FLAGS=""
+fi
+
+
+echo " "
+echo "**************** Results of filesampler package configure ****************"
+echo " "
+echo "* OpenMP Report"
+echo "*   >> Compiler support: ${have_omp}"
+echo "*   >> CFLAGS = ${OMP_FLAGS}"
+echo "* avx2 Report"
+echo "*   >> Compiler support: ${have_avx2}"
+echo "*   >> CPPFLAGS = ${AVX2_FLAGS}"
+echo "**************************************************************************"
+echo " "
+
 
 
 ac_config_files="$ac_config_files src/Makevars"
